(add-to-list 'org-latex-packages-alist '("" "minted"))
(add-to-list 'org-export-backends 'md)
(require 'org-bibtex)
(defun deactivate-c-tab ()
  "Deactivate a key in `org-mode'."
  (local-unset-key (kbd "<C-tab>")))
(add-hook 'org-mode-hook #'deactivate-c-tab)
(add-hook 'org-mode-hook #'auto-fill-mode)
(add-hook 'org-mode-hook #'(lambda () (flyspell-mode 1)))
(require 'org-mu4e)
(require 'org-ref)
(require 'org-tempo)
;; FIXME: 
(org-babel-do-load-languages
 'org-babel-load-languages
 '((dot . t)
   (emacs-lisp . t)
   (haskell . t)
   (lisp . t)
   (ocaml . t)
   (makefile . t)
   (calc . t)
   (gnuplot . t)
   (ditaa . t)
   (js . t)
   (javascript . t)
   (org . t)
   (ruby . t)
   (sql . t)
   (sqlite . t)
   (python . t)
   (rust . t)
   (plantuml . t)))
